### ISSUE TITLE
First couple clicks on 'analyze' button don't seem to do anything.

### ISSUE THREAD

**Issue by mrhappyasthma** [mrhappyasthma/IsThisStockGood#44]
It's unclear if it's a problem with the appengine instance, or the tap handling is failing, or what.

But it often takes 2-3 taps of the button before it succeeds and actually updates the UI.

**Comment by mrhappyasthma** [comment]
It seems like the logic may either be failing or hanging.

I'm seeing some logs for:
https://github.com/mrhappyasthma/IsThisStockGood/blob/708b6223d6b28a0d0f5e8fc4e20fce622b920565/src/Morningstar.py#L98

```
ERROR:root:Failed to parse EPS averages.
```

But it seems like the python is not writing back the response. I don't see the `POST` reply in the app engine log output.

**Comment by mrhappyasthma** [comment]
The first step is probably to add some more info logs to the python logic.

**Comment by mrhappyasthma** [comment]
Does not appear to occur when running locally with flask.

**Comment by mrhappyasthma** [comment]
This does not seem 100% reproducible. I suspect the problem is with one/some of the requests hanging and taking a while to actually time out.

Showing a loading affordance will help with this, but maybe having a hard-timeout would be useful too.

**Comment by mrhappyasthma** [comment]
This just occurred for the first time in a while. I need to add some more log statements to see if I can notice anything.

One theory would be that the requests could take a long time to return and don't timeout quick enough, in which case a more strict timeout on each RPC could be useful. But this is just speculation.

**Comment by kocielnik** [comment]
@mrhappyasthma, I *love* the way you've documented your analysis here!

Having read this, I feel I could pick up this issue right away where you left off.

So rare to see an analysis written down step by step like this. A wonderful example! :)

About the tool - it helps a lot in applying The Rule! Thanks a lot for sharing it!

**Comment by mrhappyasthma** [comment]
Closing this out as obsolete. I haven't seen it in a while, and we now show a nice loading spinner to denote all the loading (so early re-clicks of the button won't happen).
