### ISSUE TITLE
Margin of safety based on ttm EPS gives quite surprising result.

### ISSUE THREAD

**Issue by votientu** [mrhappyasthma/IsThisStockGood#50]
Hi,

I see that the margin of safety is calculated based on the Trailing 12 Months EPS.  

Do you think that the FCF per share is more reliable? Or the 3-year average EPS reflects better the company long-term performance in the future? 
For example, ATKR and AMD have surprisingly high EPS in 2021 because of the pandemic but that does not necessarily reflect the long-term trend.

**Comment by mrhappyasthma** [comment]
I think it's a fair question. Using a longer window of time for the EPS may help to combat relatively short term EPS fluctuations. I think the tricky thing is finding the perfect number to use (there probably isn't any 'perfect' one, but the one with the best trade-off).

I do think something like a 3-year may be a good candidate here. It's less prone to noise than the 1-year but still likely captures the trend of the company.

I guess the risk you would run would (arguably) be the exact opposite problem: a really bad TTM may be less evident when factored in to a 3 year average. But I suppose it's subjective as to whether that's a actually a problem or not. Especially given a long term time horizon and if the investor is doing their homework to keep up with the company's SEC reports.

The rule one investing formulas document just uses the "current" EPS (https://www.ruleoneinvesting.com/ExcelFormulas.pdf) but don't provide too much specifics as to how current.

**Comment by losgrandes** [comment]
We're using Yahoo API to get Trailing 12 Months EPS and this API itself is unreliable. It gives different results randomly for e.g. https://query1.finance.yahoo.com/v7/finance/quote?symbols=GOOGL.
![googl_yahoo_api_diff](https://user-images.githubusercontent.com/5540542/204128917-93dbd8da-25b6-416f-83d3-b9fdbecf49af.png)

**Comment by mrhappyasthma** [comment]
Oh wow. Good find.

Well it's out of our control to do anything with that API call, so probably our next best option is to find an alternative data source that's more stable.

**Comment by mrhappyasthma** [comment]
This is out of our control and also a bit obsolete. We now rely on MSNMoney for our sole source of data. So we are stuck with the accuracy they provide going forward.

https://github.com/mrhappyasthma/IsThisStockGood/commit/4ae7c2744ad7d1d386c5b28acf3700f9b1e75ef7
