### ISSUE TITLE
says mbuu is an invalid stock 

### ISSUE THREAD

**Issue by serhunya** [mrhappyasthma/IsThisStockGood#52]
thank you for your great work

**Comment by mrhappyasthma** [comment]
it's crashing. i think due to how i quickly parsed the new data source. ill see if i can figure it out

**Comment by mrhappyasthma** [comment]
Fixed in https://github.com/mrhappyasthma/IsThisStockGood/commit/a5709debc0be58dfc2ecf117644e512e100b5577

Also this stock looking pretty good from the numbers. Nice find.

**Comment by mrhappyasthma** [comment]
New build is deployed. Confirmed that `mbuu` is working on the main webpage.

**Comment by serhunya** [comment]
Thank you for fixing it!
