### ISSUE TITLE
Long term debt is unknown

### ISSUE THREAD

**Issue by losgrandes** [mrhappyasthma/IsThisStockGood#61]
I saw comment in the code:
TODO: Figure out how to get long-term debt instead of total deb 

I think it can be achieved by polling below endpoint.

https://assets.msn.com/service/Finance/Equities/financialstatements?apikey=0QfOX3Vn51YCzitbLaRkTTBadtWpgTN8NZLW0C1SEM&activityId=BC6BE04F-7903-4171-A666-49C66861BC18&ocid=finance-financestockdetails-Peregrine&market=en-us&fdhead=prg-1sw-spexexc,prg-1sw-exex,prg-1sw-sprtpc,prg-1sw-cocachec,1s-winauthservice,prg-1sw-wcf1,prg-1sw-fwc,prg-1sw-fwcp1,prg-1sw-sptprvmax5,1s-fcrypt,prg-1sw-gempcv5p5,prg-1sw-anid,prg-1sw-prhistcp3,prg-1sw-prdmcap3,prg-1sw-prehistory,prg-1sw-sbn-mm,1s-rpssecautht,prg-1sw-p1wtrclm,prg-1sw-wcf2,prg-1sw-fwc,prg-1sw-fwcp2,1s-brcolors,1s-cols-duo,1s-xapntpseg,prg-1sw-enablenpq-c,1s-compicsync,prg-1sw-cbm0,prg-1sw-wxsegxap,prg-1sw-multif1,prg-1sw-multifn,1s-defaultscn,prg-1sw-pde0,prg-1sw-p1svgv6,prg-1sw-p2pngv6,prg-1sw-multif2,1s-defaultscnw,prg-1sw-steat,prg-1sw-wxtsetr9,prg-1sw-wcstart,prg-1sw-tbrcounter&$filter=_p%20eq%20%27a1u3p2%27&$top=200&wrapodata=false

**Comment by losgrandes** [comment]
`$filter` param contains `SecId`, which could be identified for a given ticker in the same way it's done in https://github.com/mrhappyasthma/IsThisStockGood/pull/60.

**Comment by mrhappyasthma** [comment]
(Perhaps related: https://github.com/mrhappyasthma/IsThisStockGood/issues/39)

**Comment by mrhappyasthma** [comment]
It looks like the URL includes the API key. Do we know if this value is static or if it changes over time? (I wouldn't be surprised if it can 'expire'.) And we likely don't have a good way to determine one on-demand.

**Comment by losgrandes** [comment]
longTermDebt is also available at https://query1.finance.yahoo.com/v10/finance/quoteSummary/GOOG?modules=balanceSheetHistory

**Comment by mrhappyasthma** [comment]
The yahoo finance link is dead, but the MSN one lives on. I'll update the code to use that since the other sites are all guarded by API keys and such.
