### ISSUE TITLE
Getting "Undefined" instead of Sticker Price for NVDA and other tickers

### ISSUE THREAD

**Issue by kocielnik** [mrhappyasthma/IsThisStockGood#66]
![problem-stock-annotated](https://user-images.githubusercontent.com/17572829/236675580-ce554060-b733-4d42-be3e-3375d3d111e9.png)

**Comment by kocielnik** [comment]
Please accept a coffee as a thank you if you solve this! :)

**Comment by kocielnik** [comment]
https://app.bountysource.com/issues/120514729-getting-undefined-instead-of-sticker-price-for-nvda-and-other-tickers

**Comment by kocielnik** [comment]
![](https://img.shields.io/badge/bounties-%2415-green)

Please accept a coffee as a thank you if you solve this! :)

Claim: https://app.bountysource.com/issues/120514729-getting-undefined-instead-of-sticker-price-for-nvda-and-other-tickers

**Comment by kocielnik** [comment]
May be closed by #67.

**Comment by mrhappyasthma** [comment]
Patching #67 locally does appear to fix the problem. Once we merge it in, I can deploy it to the live version of the site.

**Comment by mrhappyasthma** [comment]
The latest version should now be deployed.

**Comment by mrhappyasthma** [comment]
@lukaqueres - There was a bug bounty for this one, so be sure to claim it.

https://app.bountysource.com/issues/120514729-getting-undefined-instead-of-sticker-price-for-nvda-and-other-tickers

Thanks again!

**Comment by lukaqueres** [comment]
You're welcome. :D
