### ISSUE TITLE
Fixes to the JS and major problem with yahoo API

### ISSUE THREAD

**Issue by lukaqueres** [mrhappyasthma/IsThisStockGood#69]
I have already fixed problem with JS loading. Loading pop-up is still displaied in case of any error, should be fixed now.

### But Yahoo

Yahoo has gone mad, and closed this `https://query1.finance.yahoo.com/v7/finance/quote?symbols={}` endpoint ( the `v6` returns `404` ). I wasted way too much time trying to find an issue, just to figure out, that there was a message ( easiest way to see: https://query1.finance.yahoo.com/v7/finance/quote?symbols=MSFT ):

![image](https://github.com/mrhappyasthma/IsThisStockGood/assets/57031937/2ff5c3b6-4450-47b6-95c5-16b1d40b8eda)

Link leads to google form:

![image](https://github.com/mrhappyasthma/IsThisStockGood/assets/57031937/6d69d302-42f8-44b1-9f07-c73be8d0fb10)

With this question especially funny:

![image](https://github.com/mrhappyasthma/IsThisStockGood/assets/57031937/355c1fa6-6595-4b18-9a11-39710af7f016)

So yea, no data from this source.

**Comment by kocielnik** [comment]
Thanks for describing your findings here in detail, @lukaqueres! :)

There may still be some other API that will provide that info for us.

The docs for Google Sheets you shared from https://support.google.com/docs/answer/3093281 also look like something that could be valuable here.

**Comment by mrhappyasthma** [comment]
Agreed. The best option here is simply to find an alternative. Sadly. :(

**Comment by mrhappyasthma** [comment]
Interestingly only the `YahooFinanceQuote` is failing. The `YahooFinanceQuoteSummary` still appears to work.

The data missing from the quote is:

1. current price
2. market cap
3. stock name (from ticker)
4. average volume per day
5. TTM EPS

Aside from 'maybe' the TTM EPS, none of the other values are anything too difficult to find from other data sources.

**Comment by mrhappyasthma** [comment]
Its been a while, so I traced where all our data comes from (to make it easier to track if an API goes down or we find a better alternative for anything):

https://github.com/mrhappyasthma/IsThisStockGood/wiki/Data-fetching---scraping-overview
