### ISSUE TITLE
Undefined values

### ISSUE THREAD

**Issue by Ladduro** [mrhappyasthma/IsThisStockGood#72]
Hi, the site is showing undefined values for fair value
<img width="1288" alt="image" src="https://github.com/mrhappyasthma/IsThisStockGood/assets/15046988/c6fe3944-4d55-4c8d-8802-d58071199b07">

**Comment by mrhappyasthma** [comment]
Yes, we lost a few data sources and haven't had the chance to find replacements.

See https://github.com/mrhappyasthma/IsThisStockGood/issues/71 and https://github.com/mrhappyasthma/IsThisStockGood/issues/69
