### ISSUE TITLE
Debt - should we consider only the long-term amount, like we did before the recent fixes?

### ISSUE THREAD

**Issue by kocielnik** [mrhappyasthma/IsThisStockGood#74]
```bash
$ curl -s https://assets.msn.com/service/Finance/QuoteSummary\?apikey\=0QfOX3Vn51YCzitbLaRkTTBadtWpgTN8NZLW0C1SEM\&ocid\=finance-utils-peregrine\&cm\=en-us\&it\=web\&scn\=MSFT\&ids\=a226gh\&intents\=Quotes,Exchanges,QuoteDetails\&wrapodata\=false | jq . > out.json
$ < out.json jq '.[0]["equity"]["analysis"]["annualStatements"]["2009"]["liabilities"]'
5.6787
$ < out.json jq '.[0]["equity"]["analysis"]["annualStatements"]["2009"]["longTermDebt"]'
0.0
```

Seems it would only take a change in a single label.

Something to pay attention to: I haven't yet checked if the unit of the label `longTermDebt` matches the unit for `liabilities` (thousands, millions, etc.).

**Comment by kocielnik** [comment]
Proposed changes: #75

**Comment by mrhappyasthma** [comment]
I think using long term debt is probably fine. It better matches what Phil Town mentioned in Rule #1, from what I recall.

Although we should also update the text label in the HTML template

**Comment by kocielnik** [comment]
> It better matches what Phil Town mentioned in Rule #1

It turns out Phil has his own Toolbox (surprise, surprise), and this toolbox (https://ruleonetoolbox.com/) also uses long-term debt specifically.

I consider this an additional confirmation we're heading in the right direction.

![debt-in-toolbox](https://github.com/mrhappyasthma/IsThisStockGood/assets/17572829/93e0d4ef-4828-4db7-9024-8fe23450e459)

**Comment by mrhappyasthma** [comment]
Fixed
