### ISSUE TITLE
Debt-to-equity ratio seems off

### ISSUE THREAD

**Issue by mrhappyasthma** [mrhappyasthma/IsThisStockGood#76]
MSFT reports 

```
Debt-to-Equity Ratio (Most recent quarter)
--
34.899
```

Which feels wrong. Some quick google search results show 0.32 - https://www.gurufocus.com/term/debt-to-equity/MSFT#:~:text=Microsoft%20(Microsoft)%20Debt%2Dto,2024)

**Comment by mrhappyasthma** [comment]
(NOTE: i didn't have time to look into the code or the payload from MSN Money yet. I just noticed this while using the site)

**Comment by kocielnik** [comment]
The original value seems to be a fraction, later converted into a percentage in the Web UI.

![debt-to-equity-msft](https://github.com/mrhappyasthma/IsThisStockGood/assets/17572829/783b0b85-f248-47be-827d-4a6e891d5e6e)

For 2023, the API-side value ([link](https://assets.msn.com/service/Finance/Equities?apikey=0QfOX3Vn51YCzitbLaRkTTBadtWpgTN8NZLW0C1SEM&activityId=75933AFA-D27A-4432-9946-F91D1693D289&ocid=finance-utils-peregrine&cm=en-us&it=web&scn=ANON&ids=a1xzim&wrapodata=false))was:

![api-value](https://github.com/mrhappyasthma/IsThisStockGood/assets/17572829/904fb66f-c86b-4090-b22a-af5c5675d20c)

**Comment by kocielnik** [comment]
Upon dividing the API-delivered value by 100 to get a percentage, the value in the app now is in agreement with the MSN Money UI:

![updated-debt-to-equity-isthisstockgood](https://github.com/mrhappyasthma/IsThisStockGood/assets/17572829/a3442cb4-cc7c-47af-8a27-8626517ff51b)

**Comment by mrhappyasthma** [comment]
Amazing. Thanks for the quick fix!

**Comment by mrhappyasthma** [comment]
deployed live.
